services:
  - type: web
    name: okanime-frontend
    env: node
    region: frankfurt
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://okanime-api.onrender.com/api
      - key: NODE_ENV
        value: production
